package(licenses = ["notice"])

load("//tools:defs.bzl", "go_library")

go_library(
    name = "kdefs",
    srcs = ["kdefs.go"],
    importpath = "gvisor.dev/gvisor/pkg/sentry/kernel/kdefs",
    visibility = ["//:sandbox"],
)
