package(licenses = ["notice"])

load("//tools:defs.bzl", "go_library")

go_library(
    name = "gtest",
    srcs = ["gtest.go"],
    importpath = "gvisor.dev/gvisor/test/syscalls/gtest",
    visibility = [
        "//test:__subpackages__",
    ],
)
