package(licenses = ["notice"])

load("//tools:defs.bzl", "go_binary")

go_binary(
    name = "dockercfg",
    srcs = ["dockercfg.go"],
    visibility = ["//visibility:public"],
    deps = ["@com_github_google_subcommands//:go_default_library"],
)
